msub$log
mfrac$mrow$\\
mfrac$mrow$msub
mfrac$mrow$msub$log
mfenced$msup
mfrac$mfenced
mfrac$mfenced$-
mfrac$mrow$+
mfrac$mfenced$+
mfenced$mfenced
mfrac$mrow$mfenced
mfrac$mrow$mfenced$-
mfrac$mrow$mfenced$+
mfenced$-
mfrac$mfenced$msup
mfrac$mrow$msup
mfrac$mrow$msup$mfenced
mfrac$mrow$msup$mfenced$mfenced
mfrac$mrow$msup$mfenced$mfenced$-
mfenced$+
mfrac$mrow$e
mfrac$mrow$mfenced$msup
msup$mfenced
msup$mfenced$\\
msup$mfenced$-
msup$mfenced$;
mfenced$\\
mfrac$mrow$mfenced$mfenced
mfrac$mrow$mfenced$mfenced$+
msup$mrow$-
mfenced$msup$mrow$-
msup$cos
mfrac$mrow$-
msup$e
mfrac$mrow$msub$mrow$-
mfrac$mfenced$\\
mfrac$mrow$msup$mrow$-
msubsup$#8747;
munderover$#8721;
munderover$mrow$=
msub$mover
msub$mover$#8721;
msub$mrow$=
msup$mfenced$+
mfrac$mrow$msqrt
mfrac$mrow$msqrt$mrow$+
msub$mrow$+
msup$mfenced$msub
msup$mrow$\\
mfrac$mfenced$mfenced
mfrac$mfenced$mfenced$+
mfrac$mrow$msup$mfenced$+
mfenced$mfenced$-
msup$mfenced$msup
mfrac$mfenced$msup$mfenced
mfrac$mfenced$msup$mfenced$+
mfrac$mfenced$msup$mrow$\\
msup$mfenced$mfrac
msup$mfenced$mfrac$mfenced
mfrac$mrow$(
mfenced$!
mfenced$#8704;
mfenced$
mfenced$#8450;
mover$#8594;
mfrac$mfenced$mfenced$
mfenced$mrow$\\
mfrac$mfenced$msup$e
mfrac$mrow$msup$e
mfrac$mrow$msup$mrow$\\
msqrt$mrow$\\
msqrt$mrow$mfrac
msqrt$mrow$mfrac$mrow$+
msqrt$mrow$mfrac$mrow$msub
mfenced$cos
mfenced$mfenced$\\
msup$mrow$mfenced
msup$mrow$mfenced$\\
msup$mrow$mfenced$+
mfenced$msup$sin
mfenced$msqrt
mfenced$msqrt$mrow$mfenced
mfenced$msqrt$mrow$mfenced$-
mfenced$msqrt$mrow$mfenced$msup
mfenced$mrow$ln
mfenced$mrow$mfenced
mfenced$mrow$mfenced$mrow$+
mfenced$mrow$+
mfenced$mfrac
mfenced$mfrac$mfenced
mfenced$mfrac$mfenced$\\
mfenced$mfrac$mfenced$cos
mfenced$mfrac$mrow$-
mfenced$mfrac$mrow$\\
mfenced$mfrac$mrow$sin
msup$tan
mfrac$mrow$msup$mfenced$msup
mfrac$mrow$msup$\\
mfrac$mrow$mfenced$\\
msup$sin
msup$mfenced$msup$cos
msup$mfenced$msup$sin
msubsup$mrow$\\
mfrac$mrow$msup$mfenced$-
msup$sec
mfenced$mrow$tan
mfrac$mrow$cos
msup$mfenced$cos
msup$mfenced$sin
msub$msup$#8747;
mfrac$mrow$msqrt$mrow$mfenced
mfrac$mrow$msqrt$mrow$mfenced$mfenced
mfrac$mrow$msqrt$mrow$mfenced$mfenced$-
mfenced$ln
mfenced$mfenced$mrow$\\
mfenced$mfenced$mrow$sec
mfenced$mfenced$mrow$+
mfenced$mfenced$mrow$tan
mfenced$mrow$sec
msubsup$mrow$-
msubsup$mrow$mfrac$mrow$\\
mfenced$sin
msup$mfenced$ln
mfenced$mfenced$msup
mfrac$mrow$msqrt$mrow$mfenced$msup
mfrac$mrow$msqrt$mrow$mfenced$-
msup$mrow$msup
mfenced$mrow$-
mfenced$mrow$msup
mfrac$mrow$mfenced$cos
mfrac$mrow$mfenced$sin
msubsup$\\
mfrac$mfenced$mfenced$\\
mfrac$mfenced$mfenced$cos
mfrac$mfenced$mfenced$-
mfrac$mfenced$mfenced$sin
msubsup$e
mfrac$mrow$mfenced$msqrt
mfrac$mrow$mfenced$msqrt$mrow$msup
mfrac$mrow$mfenced$msqrt$mrow$-
mfenced$msup$e
msqrt$mrow$+
msubsup$mrow$msqrt$mrow$-
mfrac$mrow$mfenced$msqrt$mrow$+
msub$msup
msub$msup$mrow$\\
mfenced$msup$cos
mfrac$mrow$mfenced$mfrac
mfrac$mrow$mfenced$mfrac$mrow$+
mfrac$mrow$mfenced$mfrac$mrow$msup
mfrac$mrow$mfenced$mfrac$mrow$msup$mfenced
mfrac$mrow$mfenced$mfrac$mrow$msup$mfenced$\\
mfrac$mrow$mfenced$mfrac$mrow$msup$mfenced$mfrac
mfrac$mrow$msup$mfenced$\\
mfrac$mrow$msup$mfenced$mfrac
mfrac$mrow$msup$mfenced$mfenced$msup
mfrac$mrow$msup$mfenced$mfenced$+
msup$mfenced$mfenced
msup$mfenced$mfenced$msup
msup$mfenced$mfenced$+
mfenced$|
mfrac$mrow$msup$mfenced$e
mfrac$mrow$msup$mfenced$mfenced$\\
mfenced$e
mfenced$gt;
mfenced$#8804;
mfenced$msqrt$mrow$+
mfenced$=
mfrac$mfenced$msub
mfenced$#8712;
mfenced$lt;
mfenced$#8805;
mfenced$mfenced$+
msup$
mfenced$mfrac$mfenced$-
mfenced$msub
msup$\\
mfrac$mrow$sin
msup$mfenced$#160;
msup$mfenced$tan
mfrac$mfenced$cos
mfrac$mrow$msup$sin
msup$cot
mfenced$mrow$mfrac
mfenced$mrow$mfrac$mfenced
mfenced$mrow$mfrac$mfenced$-
mfrac$mfenced$tan
mfrac$mfenced$sin
mfrac$mrow$msup$mfenced$sin
mfrac$mrow$msup$mfenced$cos
msup$mrow$msub
