INSERT INTO `DBManagement_tagdefinition` (`title`, `type`, `topic_id`, `content`) VALUE
('Decimal_And_Fraction_Conversion', 'C', 114, 'To convert a decimal to a fraction, firstly, express the decimal as a fraction with denominator depending on its place value. Then simplify the fraction to its lowest term. ; Example: 3.28 = 3\\[\\frac{28}{100}\\] = 3\\[\\frac{7}{25}\\] ; Do the opposite to convert fraction to decimal.'),
('Factors', 'C', 114, 'Factors: When a number is divided by its factor, there is no remainder. ; Example, factors of 12 = 1, 2, 3, 4, 6, 12'),
('Multiples', 'C', 114, 'When a number is multiplied by another number, the result is a multiple of the first number. ; For example: ; 4 x 1 = 4 ; 4 x 2 = 8 ; 4 x 3 = 12 ; 4 x 4 = 16 ; 4, 8, 12, 16 are some multiples of 4. ; Some multiples of 4 are: 4, 8, 12, 16, 20, 24, 28, 32, 36,... ; Some multiples of 6 are: 6, 12, 18, 24, 30, 36,.. ; Some of the common mutiples of 4 and 6 are: 12, 24, 36,...'),
('Order_Of_Operation', 'C', 114, 'Order of operation: ; 1) Do the operations in the brackets ; 2) Multiplication and division from left to right ; 3) Addition or subtraction from left to right'),
('Rounding_off', 'C', 114, 'To round off, look at previous place value, if the number if more than 5, round up, if it is less than 5, round down. ; Example: Round off 3687 to the nearest ten. ; Look at the ones value, 7 is more than 5, so round up. Answer = 3690.'),
('Number_Notations', 'C', 114, 'Example, in 8 765 432.123456: ; 2 - ones ; 3 - tens ; 4 - hundreds ; 5 - thousands ; 6 - ten thousands ; 7 - hundred thousands ; 8 - millions ; 1 - tenths ; 2 - hundredths ; 3 - thousandths ; 4 - ten thousandths ; 5 - hundred thousandths ; 6 – millionths'),
('Length_Conversion', 'C', 115, '1 km = 1000m ; 1 m = 100 cm'),
('Mass_Conversion', 'C', 115, '1 kg = 1000 g '),
('money_conversion', 'C', 115, '1 dollar = 100 cents'),
('time', 'C', 115, 'When using the 12-hour clock, we use a.m. to represent the first 12 hours of the day from midnight to 11:59 in the morning and p.m. to represent the last 12 hours of the day after noon to 11:59 at night. ; When using the 24-hour clock, we represent time by 4 digits, the first 2 digits from 00 to 23 represent the hour and the last 2 digits from 00 to 59 represent the minutes. For time from 1 p.m. to 11:59 p.m. , 12 is added to the time. For example, 1 pm = 1300 hours. '),
('Time_Conversion', 'C', 115, '1 hour = 60 minutes ; 1 minute = 60 seconds ; 1 day = 24 hours ; 1 week = 7 days ; 1 year = 12 months = 365 days'),
('volume', 'C', 115, 'Volume is the amount of space occupied by a solid shape'),
('Volume_Conversion', 'C', 115, '1 Litre = 1000 ml = 1000 \\[cm^3\\]'),
('Area_of_circle', 'F', 115, 'Area of circle = \\[\\pi\\]\\[\r^2\\]'),
('Area_Of_Square', 'F', 115, 'Area of square = length x length'),
('Area_Of_Triangle', 'F', 115, 'Area of triangle = \\[\\frac{1}{2}\\] x Base x Height'),
('Circumference_of_circle', 'F', 115, 'Circumference of circle = 2\\[\\pi\\]r'),
('Perimeter_Of_Square', 'F', 115, 'Perimeter of square = length x 4'),
('speed', 'F', 115, 'Speed = \\[\\frac{distance}{time}\\]'),
('Volume_of_cuboid', 'F', 115, 'Volume of cuboid = Length x breadth x height'),
('angles_at_a_point', 'C', 116, 'Sum of angles that meet at a point = 360\\[\\circ\\]'),
('Angles_on_a_straight_line', 'C', 116, 'Sum of angles on a straight line = 180\\[\\circ\\]'),
('equilateral_triangle', 'C', 116, 'In an equilateral triangle, there are 3 equal sides and 3 equal angles, each of which is 60\\[\\circ\\]'),
('isosceles_triangle', 'C', 116, 'In an isosceles triangle, there are 2 equal sides and the 2 angles opposite the equal sides are equal'),
('net_of_solid', 'C', 116, 'A net of solid is a 2D figure that can be cut out and folded to form the solid. ; Each solid may have more than one net'),
('parallel', 'C', 116, 'When two lines are parallel to each other, the distance between them are the same'),
('parallelogram', 'C', 116, 'In a parallelogram: ; 1) Opposite sides are equal are parallel to each other ; 2) Opposite angles are equal ; 3) Each of pair of angles between parallel sides adds up to 180\\[\\circ\\] ; 4) Area of parallelogram = base x height'),
('perpendicular', 'C', 116, 'When two lines are perpendicular to each other, the point where they meet forms a right angle'),
('rectangle', 'C', 116, 'In a rectangle: ; 1) Opposite sides are equal and opposite ; 2) Each angle is 90\\[\\circ\\]'),
('rhombus', 'C', 116, 'In rhombus: ; 1) All four sides are equal ; 2) Opposite sides are parallel ; 3) Opposite angles are equal ; 4) Each of pair angles between the parallel sides adds up to 180\\[\\circ\\]'),
('Right_angle', 'C', 116, 'Right angle = 90\\[\\circ\\]'),
('square', 'C', 116, 'In a square: ; 1) All 4 sides are equal ; 2) Each angle is 90\\[\\circ\\] ; 3) Opposite sides are parallel'),
('Sum_of_angles_in_triangle', 'C', 116, 'Sum of angles in a triangle = 180\\[\\circ\\]'),
('tessellation', 'C', 116, 'A tessellation is a repeating pattern made by fitting pieces of a unit shape together to cover a surface completely without leaving any gaps, without forming any overlaps and can be extended in all directions'),
('trapezium', 'C', 116, 'In a trapezium: ; 1) Only one pair of opposite sides is parallel ; 2) Each pair of angles between the parallel sides adds up to 180\\[\\circ\\]'),
('vertically_opposite_angles', 'C', 116, 'Vertically opposite angles are formed when two straight lines meet or cross and the angles are the same'),
('Average', 'F', 117, 'Average = \\[\\frac{Total amount}{Number of items}\\]'),
('Equivalent_Fraction', 'C', 118, 'To get equivalent fractions, we multiple or divide the numerator and denominator by the same number'),
('Fraction', 'C', 118, '\\[\\frac{a}{b}\\] = a \\[\\div\\] b'),
('Percentage_decimal_fraction', 'C', 119, 'Per cent means ''hundredth'' or ''out of 100''. Expressing a value in percentage is another way of writing a decimal or fraction with a denominator 100. The symbol % is used for percent. ; To convert a decimal to percentage, multiply the decimal by 100 by moving the decimal point 2 places to the right. Do the opposite to convert a percentage to decimal. ; To convert a fraction to percentage, multiply the fraction by 100 and express the fraction in its simplest form. Do the opposite to convert a percentage to fraction ;'),
('ratio', 'C', 119, 'Ratios are used to express two or more quantities of the same unit. ; Equivalent ratios are similar to equivalent fractions where the ratio is multiplied by the same number throughout, example, 2:1 = 6:3'),
('Percentage', 'F', 119, 'Percentage = \\[\\frac{Value}{Total}\\] x 100%'),
('Guess_and_check', 'C', 120, 'This heuristic is used to make a reasonable guess. Check the guess and revise the guess if necessary, together with systematic listing to narrow down the choices to the correct answer in the shortest possible time'),
('algebra', 'C', 121, 'In algebra, we use letters to represent unknown numbers. This allows us to make general rules that are true for all numbers. ; We can also carry out the four operations with algebraic expressions. ; For example: ; 1) The sum of a and 5 = (a + 5) ; 2) The difference between 5 and z = (5 – z) or (z – 5) ; 3) The product of g and 5 = 5 x g = 5g ; 4) The quotient obtained with z is divided by 5 = \\[\\frac{z}{5}\\]'),
('work_backwards', 'C', 120, 'This heuristic is used when the final result is given and an initial or intermediate value needs to be found, and to change the focus and reconsider the problem in reverse');
